# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.5
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace GeoHex3.swift.xcworkspace -scheme GeoHex3SwiftTests -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' -sdk iphonesimulator14.5 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
